clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - git clone --single-branch https://github.com/drone-plugins/drone-github-release
    - cd drone-github-release
    - sed -i 's/FROM alpine/FROM armhfbuild\/alpine/' Dockerfile
    - go get
    - go build
    - go test

publish:
  docker:
    context: drone-github-release
    file: drone-github-release/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfplugins/drone-github-release
    storage_driver: overlay
    when:
      repo: armhf-drone-plugins/drone-github-release
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf

plugin:
  name: GitHub Release
  desc: Publishs files and artifacts to GitHub Releases
  type: publish
  image: armhfplugins/drone-github-release
  labels:
    - github
    - release
